import { NextResponse } from "next/server";
import { ActiveRiderRoute } from "@/lib/routeOptimization/types";

export async function GET() {
  try {
    const activeRiders: ActiveRiderRoute[] = [
      {
        partnerId: "partner_1",
        partnerName: "Rajesh Kumar",
        vehicleType: "Electric Scooter",
        phone: "+91 98765 43210",
        currentLocation: { lat: 12.9716, lng: 77.5946 },
        activeOrdersCount: 2,
        currentRoute: {
          id: "route_101",
          partnerId: "partner_1",
          orderIds: ["ord_501", "ord_502"],
          mode: "fastest",
          waypoints: [
            {
              id: "wp_1",
              orderId: "ord_501",
              name: "Truffles Indiranagar",
              type: "pickup",
              sequenceOrder: 1,
              status: "completed",
              lat: 12.9784,
              lng: 77.6408,
            },
            {
              id: "wp_2",
              orderId: "ord_502",
              name: "Toit Brewpub",
              type: "pickup",
              sequenceOrder: 2,
              status: "pending",
              lat: 12.9792,
              lng: 77.6412,
            },
            {
              id: "wp_3",
              orderId: "ord_501",
              name: "Customer: Vikram S.",
              type: "dropoff",
              sequenceOrder: 3,
              status: "pending",
              lat: 12.9654,
              lng: 77.6521,
            },
          ],
          polyline: "12.9716,77.5946;12.9784,77.6408;12.9792,77.6412;12.9654,77.6521",
          coordinates: [
            { lat: 12.9716, lng: 77.5946 },
            { lat: 12.9784, lng: 77.6408 },
            { lat: 12.9792, lng: 77.6412 },
            { lat: 12.9654, lng: 77.6521 },
          ],
          totalDistanceKm: 6.8,
          totalDurationMin: 19,
          trafficLevel: "normal",
          optimizationScore: {
            totalScore: 94,
            distanceScore: 92,
            timeScore: 95,
            fuelScore: 98,
            onTimeProbability: 96,
          },
          fuelEstimate: {
            estimatedLiters: 0.0,
            estimatedCost: 0,
            co2Gram: 0,
            savingsVsDefault: 22,
          },
          turnInstructions: [
            { instruction: "Head East on 100ft Road", distanceKm: 2.1, durationMin: 6, type: "straight", location: { lat: 12.9716, lng: 77.5946 } },
            { instruction: "Turn right onto 12th Main", distanceKm: 1.5, durationMin: 5, type: "turn", location: { lat: 12.9784, lng: 77.6408 } },
          ],
          nextStop: {
            id: "wp_2",
            orderId: "ord_502",
            name: "Toit Brewpub",
            type: "pickup",
            sequenceOrder: 2,
            status: "pending",
            lat: 12.9792,
            lng: 77.6412,
          },
          remainingDistanceKm: 4.7,
          remainingDurationMin: 13,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
        efficiencyScore: 94,
        status: "on_route",
        speedKmH: 28,
        lastUpdated: new Date().toISOString(),
      },
      {
        partnerId: "partner_2",
        partnerName: "Suresh Patil",
        vehicleType: "Motorcycle",
        phone: "+91 98123 45678",
        currentLocation: { lat: 12.9352, lng: 77.6245 },
        activeOrdersCount: 1,
        currentRoute: {
          id: "route_102",
          partnerId: "partner_2",
          orderIds: ["ord_503"],
          mode: "lowest_traffic",
          waypoints: [
            {
              id: "wp_4",
              orderId: "ord_503",
              name: "Meghana Foods Koramangala",
              type: "pickup",
              sequenceOrder: 1,
              status: "completed",
              lat: 12.9352,
              lng: 77.6245,
            },
            {
              id: "wp_5",
              orderId: "ord_503",
              name: "Customer: Priya R. (Express)",
              type: "dropoff",
              sequenceOrder: 2,
              status: "pending",
              lat: 12.9121,
              lng: 77.6445,
            },
          ],
          polyline: "12.9352,77.6245;12.9121,77.6445",
          coordinates: [
            { lat: 12.9352, lng: 77.6245 },
            { lat: 12.9121, lng: 77.6445 },
          ],
          totalDistanceKm: 3.4,
          totalDurationMin: 11,
          trafficLevel: "heavy",
          optimizationScore: {
            totalScore: 88,
            distanceScore: 86,
            timeScore: 90,
            fuelScore: 85,
            onTimeProbability: 92,
          },
          fuelEstimate: {
            estimatedLiters: 0.1,
            estimatedCost: 10,
            co2Gram: 239,
            savingsVsDefault: 18,
          },
          turnInstructions: [],
          nextStop: {
            id: "wp_5",
            orderId: "ord_503",
            name: "Customer: Priya R. (Express)",
            type: "dropoff",
            sequenceOrder: 2,
            status: "pending",
            lat: 12.9121,
            lng: 77.6445,
          },
          remainingDistanceKm: 3.4,
          remainingDurationMin: 11,
          createdAt: new Date().toISOString(),
          updatedAt: new Date().toISOString(),
        },
        efficiencyScore: 88,
        status: "at_pickup",
        speedKmH: 0,
        lastUpdated: new Date().toISOString(),
      },
      {
        partnerId: "partner_3",
        partnerName: "Amit Sharma",
        vehicleType: "Scooter",
        phone: "+91 97654 32109",
        currentLocation: { lat: 12.9116, lng: 77.6389 },
        activeOrdersCount: 1,
        currentRoute: null,
        efficiencyScore: 91,
        status: "idle",
        speedKmH: 0,
        lastUpdated: new Date().toISOString(),
      },
    ];

    return NextResponse.json({
      success: true,
      data: activeRiders,
    });
  } catch (error: any) {
    return NextResponse.json(
      { success: false, error: error.message || "Failed to fetch admin routes" },
      { status: 500 }
    );
  }
}
